### PR TITLE
fix: make view cart addons responsive

### PR DESCRIPTION
**Pull request by bhardwajpriyanshu1208**
## Description
make view cart addons responsive for smaller screens.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Changes and Fixes
grid template columns set to  autofit and provided a smaller min-width for smaller screens.

## Screenshots 
image
image
image

## Checklist
- [ ] Database schema is updated
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Looks good on large screens
- [x] Looks good on mobiles
- [x] Looks good on Tablets

Affected Apps
- [x] Store
    - [ ] SEO
    - [ ] Menu
    - [ ] Checkout
    - [ ] Add to Cart logic
    - [ ] Location Logic
    - [ ] Product page
    - [ ] Login
    - [ ] Payment
    - [ ] Kiosk
- [ ] Admin
    - [ ] Order
    - [ ] CRM
    - [ ] Product app
    - [ ] Analytics
    - [ ] Settings
    - [ ] Brand
    - [ ] Config Builder
    - [ ] Coupons
    - [ ] Locations
    - [ ] Users
    - [ ] Inventory
- [ ] Server
    - [ ] Payment
    - [ ] Email
    - [ ] SMS
    - [ ] Notifications
    - [ ] Integration
    - [ ] Hasura auth
- [ ] Template Engine

### CODE REVIEW

**Review by FAsami — COMMENTED** [review]
- Can we make the button size a bit smaller so that it looks good on smaller devices? 
image

- And the close is taking up more spaces I think 
image

**Comment by bhardwajpriyanshu1208** [comment]
> * Can we make the button size a bit smaller so that it looks good on smaller devices?
> 
> image
> 
> * And the close is taking up more spaces I think
> 
> image

image
how about this? @FAsami

**Comment by FAsami** [comment]
> image how about this? @FAsami

Looks great. Can you please check the close button as well? It looks like it has moved a bit where it is supposed to be.

**Comment by bhardwajpriyanshu1208** [comment]
check now @FAsami

**Comment by valeshgopal** [comment]
Also, pls change font-family of texts on Add-on popup to var(--hern-primary-font)

**Review by FAsami — APPROVED** [review]

**Review by valeshgopal — APPROVED** [review]

**Pull request merged**
