### PR TITLE
Fix/changing cart UI

### PR DESCRIPTION
**Pull request by Sourav635**
## Description
Made changes in Cart UI

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Changes and Fixes
- Added Margin between left section and header
- Adjusted padding & margin from side ends of a component
- Changed background color of UI components based on their activeness i.e., if component is active its bgColor is white else off-white

## Screenshots 
image
image
image

## Checklist
- [ ] Database schema is updated
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Looks good on large screens
- [x] Looks good on mobiles
- [x] Looks good on Tablets

Affected Apps
- [x] Store
    - [ ] SEO
    - [ ] Menu
    - [x] Checkout
    - [ ] Add to Cart logic
    - [ ] Location Logic
    - [ ] Product page
    - [ ] Login
    - [ ] Payment
    - [ ] Kiosk
- [ ] Admin
    - [ ] Order
    - [ ] CRM
    - [ ] Product app
    - [ ] Analytics
    - [ ] Settings
    - [ ] Brand
    - [ ] Config Builder
    - [ ] Coupons
    - [ ] Locations
    - [ ] Users
    - [ ] Inventory
- [ ] Server
    - [ ] Payment
    - [ ] Email
    - [ ] SMS
    - [ ] Notifications
    - [ ] Integration
    - [ ] Hasura auth
- [ ] Template Engine

### CODE REVIEW

**Comment by valeshgopal** [comment]
Sourav, pls fix the box-shadow issue of the components too. The right side looks faded. It usually happens if one the parents has overflow property. Pls check

**Review by FAsami — COMMENTED** [review]
image
Please remove the border and extra spaces when it is closed.

**Comment by valeshgopal** [comment]
Screenshot 2022-09-23 103510

Please fix the mobile view

**Comment by FAsami** [comment]
@valeshgopal  updated this on a different branch

**Pull request closed without merging**
